language: node_js
node_js:
- '7'

sudo: required

env:
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost

services:
  - postgresql
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
  password: postgres
before_script:
- npm install -g gulp-cli
- "psql -c 'create database apitest;' -U postgres"
- "sequelize db:migrate"
- "rake db:migrate"