language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install: [ "npm install"]
addons:
  coveralls:
    coveralls: vYZo0Iba9NM0IYHjWYIy3QyoM5ZCptb9G
after_script:
  - ./node_modules/.bin/gulp coveralls
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info